apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    env: staging
  name: nginx
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      env: staging
  template:
    metadata:
      labels:
        app: nginx
        env: staging
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
