apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-prod-helm
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: 'git@github.com:sunil-nagendra/argocd-nginx-test-deployment.git'
    targetRevision: HEAD
    path: '.'
    helm:
      valueFiles:
        - configs/values-prod.yaml
  destination:
    server: 'https://192.168.91.245:6443'
    namespace: prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

